---
version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node:14.17.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install --frozen-lockfile --ignore-engines
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn build
      - run: yarn lint
      - run: yarn test

workflows:
  version: 2
  build_test:
    jobs:
      - build_test
